# Generated by Django 5.0.6 on 2024-06-12 20:57

import django.db.models.deletion
import django.utils.timezone
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('location', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ تولد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت اطلاعات')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی اطلاعات')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[shared.validators.validate_numeric], verbose_name='شماره تلفن')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='customer.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'شماره تلفن',
                'verbose_name_plural': 'شماره تلفن\u200cها',
            },
        ),
    ]
