# Generated by Django 5.0.6 on 2024-06-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('1', 'موبایل'), ('2', 'کتاب، لوازم تحریر و هنر'), ('3', 'کالای دیجیتال'), ('4', 'خانه و آشپزخانه'), ('5', 'لوازم خانگی برقی'), ('6', 'مد و پوشاک'), ('7', 'ساعت، طلا و جواهرات'), ('8', 'آرایشی بهداشتی'), ('9', 'تجهیزات پزشکی و سلامت'), ('10', 'ورزش و سفر'), ('11', 'کارت هدیه و گیفت کارت'), ('12', 'کالاهای سوپرمارکتی'), ('13', 'اسباب بازی، کودک و نوزاد'), ('14', 'ابزار آلات و تجهیزات'), ('15', 'خودرو و موتورسیکلت'), ('16', 'محصولات بومی و محلی'), ('17', 'دیگر')], max_length=2, verbose_name='دسته بندی کسب و کار'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اکانت'),
        ),
    ]
