# Generated by Django 5.0.6 on 2024-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseinvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='value_added',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد ارزش افزوده محصول'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='value_added',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد ارزش افزوده فاکتور'),
        ),
    ]
