# Generated by Django 5.0.6 on 2024-06-12 20:57

import django.db.models.deletion
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تامین کننده')),
                ('location', models.TextField(blank=True, null=True, unique=True, verbose_name='آدرس')),
                ('website', models.URLField(blank=True, null=True, unique=True, verbose_name='وبسایت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت اطلاعات')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی اطلاعات')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کننده ها',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[shared.validators.validate_numeric], verbose_name='شماره تلفن')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'شماره تلفن',
                'verbose_name_plural': 'شماره تلفن\u200cها',
            },
        ),
    ]
