# Generated by Django 5.0.6 on 2024-06-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'تامین کننده', 'verbose_name_plural': 'تامین کننده\u200cها'},
        ),
    ]
